import type { ApplicationRecord, SessionSummary, ProfessionalProfile } from '@job-agent/core';

/** Status badge for Markdown */
const STATUS_EMOJI: Record<string, string> = {
  applied: '✅',
  easy_apply_not_available: '⚠️',
  already_applied: '🔁',
  failed: '❌',
  skipped_low_score: '⏭️',
};

/** Status badge for HTML */
const STATUS_HTML_CLASS: Record<string, string> = {
  applied: 'badge-success',
  easy_apply_not_available: 'badge-warning',
  already_applied: 'badge-info',
  failed: 'badge-danger',
  skipped_low_score: 'badge-secondary',
};

/**
 * Generates the Markdown report for a completed session.
 * @param records - All application records from the session.
 * @param summary - Session summary statistics.
 * @param profile - The candidate's professional profile.
 * @returns A Markdown string.
 */
export function generateMarkdownReport(
  records: ApplicationRecord[],
  summary: SessionSummary,
  profile: ProfessionalProfile
): string {
  const duration = Math.round(summary.durationSeconds / 60);

  const lines: string[] = [
    `# LinkedIn Job Application Report`,
    ``,
    `> Generated: ${new Date(summary.sessionEndedAt).toLocaleString()}`,
    ``,
    `## 👤 Candidate`,
    ``,
    `| Field | Value |`,
    `|-------|-------|`,
    `| Name | ${profile.fullName} |`,
    `| Seniority | ${profile.seniority} |`,
    `| Experience | ${profile.yearsOfExperience} years |`,
    `| Tech Stack | ${profile.techStack.slice(0, 8).join(', ')} |`,
    ``,
    `## 📊 Session Summary`,
    ``,
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Jobs Found | ${summary.totalFound} |`,
    `| Jobs Scored | ${summary.totalScored} |`,
    `| Applications Sent | **${summary.totalApplied}** |`,
    `| Skipped (low score) | ${summary.totalSkipped} |`,
    `| Failed | ${summary.totalFailed} |`,
    `| Duration | ${duration} min |`,
    ``,
    `## 📋 Applications`,
    ``,
  ];

  // Applied first, then by score
  const sorted = [...records].sort((a, b) => {
    if (a.status === 'applied' && b.status !== 'applied') return -1;
    if (b.status === 'applied' && a.status !== 'applied') return 1;
    return b.job.compatibilityScore - a.job.compatibilityScore;
  });

  for (const record of sorted) {
    const { job, status, appliedAt, errorMessage } = record;
    const emoji = STATUS_EMOJI[status] ?? '❓';
    const score = job.compatibilityScore;

    lines.push(`### ${emoji} ${job.title}`);
    lines.push(`**${job.company}** · ${job.location} · ${job.modality}`);
    lines.push(`Score: **${score}/100** · Status: \`${status}\` · Applied: ${new Date(appliedAt).toLocaleString()}`);
    if (errorMessage) lines.push(`> ⚠️ Error: ${errorMessage}`);
    lines.push(`[View Job](${job.applyUrl})`);
    lines.push('');
  }

  lines.push(`---`);
  lines.push(`*Generated by Job Agent — Use responsibly. Respect LinkedIn's Terms of Service.*`);

  return lines.join('\n');
}

/**
 * Generates a self-contained HTML report for a completed session.
 * @param records - All application records from the session.
 * @param summary - Session summary statistics.
 * @param profile - The candidate's professional profile.
 * @returns An HTML string.
 */
export function generateHtmlReport(
  records: ApplicationRecord[],
  summary: SessionSummary,
  profile: ProfessionalProfile
): string {
  const duration = Math.round(summary.durationSeconds / 60);
  const generatedAt = new Date(summary.sessionEndedAt).toLocaleString();

  const sorted = [...records].sort((a, b) => {
    if (a.status === 'applied' && b.status !== 'applied') return -1;
    if (b.status === 'applied' && a.status !== 'applied') return 1;
    return b.job.compatibilityScore - a.job.compatibilityScore;
  });

  const rows = sorted.map((record) => {
    const { job, status, appliedAt } = record;
    const badgeClass = STATUS_HTML_CLASS[status] ?? 'badge-secondary';
    const scoreColor = job.compatibilityScore >= 80 ? '#10b981' : job.compatibilityScore >= 60 ? '#f59e0b' : '#ef4444';

    return `
      <tr>
        <td><a href="${job.applyUrl}" target="_blank" rel="noopener">${escapeHtml(job.title)}</a></td>
        <td>${escapeHtml(job.company)}</td>
        <td>${escapeHtml(job.location)}</td>
        <td><span class="modality-badge">${job.modality}</span></td>
        <td><span class="score-pill" style="background:${scoreColor}20;color:${scoreColor};border:1px solid ${scoreColor}40">${job.compatibilityScore}</span></td>
        <td><span class="badge ${badgeClass}">${status.replace(/_/g, ' ')}</span></td>
        <td>${new Date(appliedAt).toLocaleDateString()}</td>
      </tr>`;
  }).join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Job Application Report — ${escapeHtml(profile.fullName)}</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #0f0f13; color: #e2e8f0; min-height: 100vh; padding: 2rem; }
    .container { max-width: 1200px; margin: 0 auto; }
    h1 { font-size: 2rem; font-weight: 700; background: linear-gradient(135deg, #6366f1, #8b5cf6); -webkit-background-clip: text; -webkit-text-fill-color: transparent; margin-bottom: 0.25rem; }
    .subtitle { color: #64748b; margin-bottom: 2rem; font-size: 0.875rem; }
    .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 1rem; margin-bottom: 2rem; }
    .stat-card { background: #1e1e2e; border: 1px solid #2d2d3f; border-radius: 12px; padding: 1.25rem; }
    .stat-card .label { font-size: 0.75rem; color: #64748b; text-transform: uppercase; letter-spacing: 0.05em; }
    .stat-card .value { font-size: 2rem; font-weight: 700; color: #6366f1; margin-top: 0.25rem; }
    .stat-card.success .value { color: #10b981; }
    .stat-card.danger .value { color: #ef4444; }
    table { width: 100%; border-collapse: collapse; background: #1e1e2e; border-radius: 12px; overflow: hidden; border: 1px solid #2d2d3f; }
    thead { background: #2d2d3f; }
    th { padding: 0.875rem 1rem; text-align: left; font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.05em; color: #94a3b8; font-weight: 600; }
    td { padding: 0.875rem 1rem; border-top: 1px solid #2d2d3f; font-size: 0.875rem; }
    tr:hover td { background: #252535; }
    a { color: #818cf8; text-decoration: none; }
    a:hover { text-decoration: underline; }
    .score-pill { padding: 0.2rem 0.6rem; border-radius: 999px; font-size: 0.8rem; font-weight: 600; }
    .badge { padding: 0.2rem 0.6rem; border-radius: 6px; font-size: 0.75rem; font-weight: 500; text-transform: capitalize; }
    .badge-success { background: #10b98120; color: #10b981; }
    .badge-warning { background: #f59e0b20; color: #f59e0b; }
    .badge-danger { background: #ef444420; color: #ef4444; }
    .badge-info { background: #3b82f620; color: #3b82f6; }
    .badge-secondary { background: #64748b20; color: #94a3b8; }
    .modality-badge { font-size: 0.75rem; color: #94a3b8; }
    .profile-card { background: #1e1e2e; border: 1px solid #2d2d3f; border-radius: 12px; padding: 1.25rem; margin-bottom: 2rem; display: flex; gap: 2rem; flex-wrap: wrap; }
    .profile-card h2 { font-size: 1.125rem; margin-bottom: 1rem; color: #e2e8f0; }
    .tech-tags { display: flex; flex-wrap: wrap; gap: 0.4rem; margin-top: 0.5rem; }
    .tech-tag { background: #6366f120; color: #818cf8; padding: 0.2rem 0.6rem; border-radius: 6px; font-size: 0.75rem; }
    footer { margin-top: 3rem; text-align: center; color: #475569; font-size: 0.75rem; }
  </style>
</head>
<body>
  <div class="container">
    <h1>Job Application Report</h1>
    <p class="subtitle">Generated ${generatedAt}</p>

    <div class="profile-card">
      <div>
        <h2>👤 ${escapeHtml(profile.fullName)}</h2>
        <p style="color:#94a3b8">${escapeHtml(profile.headline)}</p>
        <p style="color:#64748b;font-size:0.8rem;margin-top:0.25rem">${profile.seniority} · ${profile.yearsOfExperience} years exp</p>
      </div>
      <div>
        <p style="font-size:0.75rem;color:#64748b;text-transform:uppercase;letter-spacing:0.05em">Tech Stack</p>
        <div class="tech-tags">
          ${profile.techStack.slice(0, 12).map((t) => `<span class="tech-tag">${escapeHtml(t)}</span>`).join('')}
        </div>
      </div>
    </div>

    <div class="grid">
      <div class="stat-card success">
        <div class="label">Applied</div>
        <div class="value">${summary.totalApplied}</div>
      </div>
      <div class="stat-card">
        <div class="label">Found</div>
        <div class="value">${summary.totalFound}</div>
      </div>
      <div class="stat-card">
        <div class="label">Skipped</div>
        <div class="value">${summary.totalSkipped}</div>
      </div>
      <div class="stat-card danger">
        <div class="label">Failed</div>
        <div class="value">${summary.totalFailed}</div>
      </div>
      <div class="stat-card">
        <div class="label">Duration</div>
        <div class="value">${duration}m</div>
      </div>
    </div>

    <table>
      <thead>
        <tr>
          <th>Position</th>
          <th>Company</th>
          <th>Location</th>
          <th>Modality</th>
          <th>Score</th>
          <th>Status</th>
          <th>Date</th>
        </tr>
      </thead>
      <tbody>${rows}</tbody>
    </table>

    <footer>
      <p>Generated by <strong>Job Agent</strong> · ⚠️ Use responsibly. Respect LinkedIn's Terms of Service.</p>
    </footer>
  </div>
</body>
</html>`;
}

/** Safely escapes HTML special characters */
function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}
